version: '3'
services:
  application:
    image: kesshin/development:v1.6
    container_name: monito-application
    command: runuser node -c 'yarn dev'
    # cpu_percent: 35
    working_dir: /home/data/Presentation/Monito.Web
    env_file: .env
    depends_on:
      - database
    ports:
      - 127.0.0.1:8008:8008
      - 127.0.0.1:44013:44413
    volumes:
      - .:/home/data
    links:
      - database
  worker:
    image: kesshin/development:v1.6
    container_name: monito-worker
    working_dir: /home/data/Presentation/Monito.Worker
    restart: always
    command: go run . --simple --basic --priority
    # cpu_percent: 25
    depends_on:
      - database
    volumes:
      - .:/home/data
    links:
      - database
  database:
    image: mysql:8.0.18
    container_name: monito-database
    command: --default-authentication-plugin=mysql_native_password
    # cpu_percent: 35
    restart: always
    env_file: .env
    volumes:
      - ./Infrastructure/DatabaseScripts.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306