version: '2.2'
services:
  application:
    build:
      context: Presentation/Monito.Web
      dockerfile: docker/Dockerfile
    container_name: monito-application
    command: /app/Monito.Web
    environment: 
      ASPNETCORE_ENVIRONMENT: Production
    cpu_percent: 35
    depends_on:
      - database
    ports:
      - 127.0.0.1:8008:8008
    volumes:
      - .:/home/data
    links:
      - database
  worker:
    build:
      context: Presentation/Monito.Worker
      dockerfile: docker/Dockerfile
    container_name: monito-worker
    command: /app/Monito.Worker --simple --basic --batch
    restart: always
    cpu_percent: 25
    depends_on:
      - database
    links:
      - database
  database:
    image: mysql:8.0.18
    container_name: monito-database
    command: --default-authentication-plugin=mysql_native_password
    cpu_percent: 35
    restart: always
    env_file: .env.production
    volumes:
      - ./Infrastructure/DatabaseScripts.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.data.prod:/var/lib/mysql